# Generated by Django 4.2.1 on 2023-06-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_delete_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
